workflows:
  build-ios:
    name: Build iOS (Capacitor)
    environment:
      node: 20
      cocoapods: default
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build web app
        script: npm run build
      - name: Sync with Capacitor
        script: npx cap sync ios
      - name: Build iOS app
        script: xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release
    artifacts:
      - ios/App/build/**/*.ipa